var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
export let CallLog = (() => {
    let _classDecorators = [Schema()];
    let _classDescriptor;
    let _classExtraInitializers = [];
    let _classThis;
    let _instanceExtraInitializers = [];
    let _AccountSid_decorators;
    let _AccountSid_initializers = [];
    let _ApiVersion_decorators;
    let _ApiVersion_initializers = [];
    let _CallSid_decorators;
    let _CallSid_initializers = [];
    let _CallStatus_decorators;
    let _CallStatus_initializers = [];
    let _Called_decorators;
    let _Called_initializers = [];
    let _CalledCity_decorators;
    let _CalledCity_initializers = [];
    let _CalledCountry_decorators;
    let _CalledCountry_initializers = [];
    let _CalledState_decorators;
    let _CalledState_initializers = [];
    let _CalledZip_decorators;
    let _CalledZip_initializers = [];
    let _Caller_decorators;
    let _Caller_initializers = [];
    let _CallerCity_decorators;
    let _CallerCity_initializers = [];
    let _CallerCountry_decorators;
    let _CallerCountry_initializers = [];
    let _CallerState_decorators;
    let _CallerState_initializers = [];
    let _CallerZip_decorators;
    let _CallerZip_initializers = [];
    let _DialBridged_decorators;
    let _DialBridged_initializers = [];
    let _DialCallDuration_decorators;
    let _DialCallDuration_initializers = [];
    let _DialCallSid_decorators;
    let _DialCallSid_initializers = [];
    let _DialCallStatus_decorators;
    let _DialCallStatus_initializers = [];
    let _Direction_decorators;
    let _Direction_initializers = [];
    let _From_decorators;
    let _From_initializers = [];
    let _FromCity_decorators;
    let _FromCity_initializers = [];
    let _FromCountry_decorators;
    let _FromCountry_initializers = [];
    let _FromState_decorators;
    let _FromState_initializers = [];
    let _FromZip_decorators;
    let _FromZip_initializers = [];
    let _To_decorators;
    let _To_initializers = [];
    let _ToCity_decorators;
    let _ToCity_initializers = [];
    let _ToCountry_decorators;
    let _ToCountry_initializers = [];
    let _ToState_decorators;
    let _ToState_initializers = [];
    let _ToZip_decorators;
    let _ToZip_initializers = [];
    let _CreatedAt_decorators;
    let _CreatedAt_initializers = [];
    var CallLog = _classThis = class {
        constructor() {
            this.AccountSid = (__runInitializers(this, _instanceExtraInitializers), __runInitializers(this, _AccountSid_initializers, void 0));
            this.ApiVersion = __runInitializers(this, _ApiVersion_initializers, void 0);
            this.CallSid = __runInitializers(this, _CallSid_initializers, void 0);
            this.CallStatus = __runInitializers(this, _CallStatus_initializers, void 0);
            this.Called = __runInitializers(this, _Called_initializers, void 0);
            this.CalledCity = __runInitializers(this, _CalledCity_initializers, void 0);
            this.CalledCountry = __runInitializers(this, _CalledCountry_initializers, void 0);
            this.CalledState = __runInitializers(this, _CalledState_initializers, void 0);
            this.CalledZip = __runInitializers(this, _CalledZip_initializers, void 0);
            this.Caller = __runInitializers(this, _Caller_initializers, void 0);
            this.CallerCity = __runInitializers(this, _CallerCity_initializers, void 0);
            this.CallerCountry = __runInitializers(this, _CallerCountry_initializers, void 0);
            this.CallerState = __runInitializers(this, _CallerState_initializers, void 0);
            this.CallerZip = __runInitializers(this, _CallerZip_initializers, void 0);
            this.DialBridged = __runInitializers(this, _DialBridged_initializers, void 0);
            this.DialCallDuration = __runInitializers(this, _DialCallDuration_initializers, void 0);
            this.DialCallSid = __runInitializers(this, _DialCallSid_initializers, void 0);
            this.DialCallStatus = __runInitializers(this, _DialCallStatus_initializers, void 0);
            this.Direction = __runInitializers(this, _Direction_initializers, void 0);
            this.From = __runInitializers(this, _From_initializers, void 0);
            this.FromCity = __runInitializers(this, _FromCity_initializers, void 0);
            this.FromCountry = __runInitializers(this, _FromCountry_initializers, void 0);
            this.FromState = __runInitializers(this, _FromState_initializers, void 0);
            this.FromZip = __runInitializers(this, _FromZip_initializers, void 0);
            this.To = __runInitializers(this, _To_initializers, void 0);
            this.ToCity = __runInitializers(this, _ToCity_initializers, void 0);
            this.ToCountry = __runInitializers(this, _ToCountry_initializers, void 0);
            this.ToState = __runInitializers(this, _ToState_initializers, void 0);
            this.ToZip = __runInitializers(this, _ToZip_initializers, void 0);
            this.CreatedAt = __runInitializers(this, _CreatedAt_initializers, void 0);
        }
    };
    __setFunctionName(_classThis, "CallLog");
    (() => {
        _AccountSid_decorators = [Prop()];
        _ApiVersion_decorators = [Prop()];
        _CallSid_decorators = [Prop()];
        _CallStatus_decorators = [Prop()];
        _Called_decorators = [Prop()];
        _CalledCity_decorators = [Prop()];
        _CalledCountry_decorators = [Prop()];
        _CalledState_decorators = [Prop()];
        _CalledZip_decorators = [Prop()];
        _Caller_decorators = [Prop()];
        _CallerCity_decorators = [Prop()];
        _CallerCountry_decorators = [Prop()];
        _CallerState_decorators = [Prop()];
        _CallerZip_decorators = [Prop()];
        _DialBridged_decorators = [Prop()];
        _DialCallDuration_decorators = [Prop()];
        _DialCallSid_decorators = [Prop()];
        _DialCallStatus_decorators = [Prop()];
        _Direction_decorators = [Prop()];
        _From_decorators = [Prop()];
        _FromCity_decorators = [Prop()];
        _FromCountry_decorators = [Prop()];
        _FromState_decorators = [Prop()];
        _FromZip_decorators = [Prop()];
        _To_decorators = [Prop()];
        _ToCity_decorators = [Prop()];
        _ToCountry_decorators = [Prop()];
        _ToState_decorators = [Prop()];
        _ToZip_decorators = [Prop()];
        _CreatedAt_decorators = [Prop()];
        __esDecorate(null, null, _AccountSid_decorators, { kind: "field", name: "AccountSid", static: false, private: false, access: { has: obj => "AccountSid" in obj, get: obj => obj.AccountSid, set: (obj, value) => { obj.AccountSid = value; } } }, _AccountSid_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _ApiVersion_decorators, { kind: "field", name: "ApiVersion", static: false, private: false, access: { has: obj => "ApiVersion" in obj, get: obj => obj.ApiVersion, set: (obj, value) => { obj.ApiVersion = value; } } }, _ApiVersion_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _CallSid_decorators, { kind: "field", name: "CallSid", static: false, private: false, access: { has: obj => "CallSid" in obj, get: obj => obj.CallSid, set: (obj, value) => { obj.CallSid = value; } } }, _CallSid_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _CallStatus_decorators, { kind: "field", name: "CallStatus", static: false, private: false, access: { has: obj => "CallStatus" in obj, get: obj => obj.CallStatus, set: (obj, value) => { obj.CallStatus = value; } } }, _CallStatus_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _Called_decorators, { kind: "field", name: "Called", static: false, private: false, access: { has: obj => "Called" in obj, get: obj => obj.Called, set: (obj, value) => { obj.Called = value; } } }, _Called_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _CalledCity_decorators, { kind: "field", name: "CalledCity", static: false, private: false, access: { has: obj => "CalledCity" in obj, get: obj => obj.CalledCity, set: (obj, value) => { obj.CalledCity = value; } } }, _CalledCity_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _CalledCountry_decorators, { kind: "field", name: "CalledCountry", static: false, private: false, access: { has: obj => "CalledCountry" in obj, get: obj => obj.CalledCountry, set: (obj, value) => { obj.CalledCountry = value; } } }, _CalledCountry_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _CalledState_decorators, { kind: "field", name: "CalledState", static: false, private: false, access: { has: obj => "CalledState" in obj, get: obj => obj.CalledState, set: (obj, value) => { obj.CalledState = value; } } }, _CalledState_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _CalledZip_decorators, { kind: "field", name: "CalledZip", static: false, private: false, access: { has: obj => "CalledZip" in obj, get: obj => obj.CalledZip, set: (obj, value) => { obj.CalledZip = value; } } }, _CalledZip_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _Caller_decorators, { kind: "field", name: "Caller", static: false, private: false, access: { has: obj => "Caller" in obj, get: obj => obj.Caller, set: (obj, value) => { obj.Caller = value; } } }, _Caller_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _CallerCity_decorators, { kind: "field", name: "CallerCity", static: false, private: false, access: { has: obj => "CallerCity" in obj, get: obj => obj.CallerCity, set: (obj, value) => { obj.CallerCity = value; } } }, _CallerCity_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _CallerCountry_decorators, { kind: "field", name: "CallerCountry", static: false, private: false, access: { has: obj => "CallerCountry" in obj, get: obj => obj.CallerCountry, set: (obj, value) => { obj.CallerCountry = value; } } }, _CallerCountry_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _CallerState_decorators, { kind: "field", name: "CallerState", static: false, private: false, access: { has: obj => "CallerState" in obj, get: obj => obj.CallerState, set: (obj, value) => { obj.CallerState = value; } } }, _CallerState_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _CallerZip_decorators, { kind: "field", name: "CallerZip", static: false, private: false, access: { has: obj => "CallerZip" in obj, get: obj => obj.CallerZip, set: (obj, value) => { obj.CallerZip = value; } } }, _CallerZip_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _DialBridged_decorators, { kind: "field", name: "DialBridged", static: false, private: false, access: { has: obj => "DialBridged" in obj, get: obj => obj.DialBridged, set: (obj, value) => { obj.DialBridged = value; } } }, _DialBridged_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _DialCallDuration_decorators, { kind: "field", name: "DialCallDuration", static: false, private: false, access: { has: obj => "DialCallDuration" in obj, get: obj => obj.DialCallDuration, set: (obj, value) => { obj.DialCallDuration = value; } } }, _DialCallDuration_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _DialCallSid_decorators, { kind: "field", name: "DialCallSid", static: false, private: false, access: { has: obj => "DialCallSid" in obj, get: obj => obj.DialCallSid, set: (obj, value) => { obj.DialCallSid = value; } } }, _DialCallSid_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _DialCallStatus_decorators, { kind: "field", name: "DialCallStatus", static: false, private: false, access: { has: obj => "DialCallStatus" in obj, get: obj => obj.DialCallStatus, set: (obj, value) => { obj.DialCallStatus = value; } } }, _DialCallStatus_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _Direction_decorators, { kind: "field", name: "Direction", static: false, private: false, access: { has: obj => "Direction" in obj, get: obj => obj.Direction, set: (obj, value) => { obj.Direction = value; } } }, _Direction_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _From_decorators, { kind: "field", name: "From", static: false, private: false, access: { has: obj => "From" in obj, get: obj => obj.From, set: (obj, value) => { obj.From = value; } } }, _From_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _FromCity_decorators, { kind: "field", name: "FromCity", static: false, private: false, access: { has: obj => "FromCity" in obj, get: obj => obj.FromCity, set: (obj, value) => { obj.FromCity = value; } } }, _FromCity_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _FromCountry_decorators, { kind: "field", name: "FromCountry", static: false, private: false, access: { has: obj => "FromCountry" in obj, get: obj => obj.FromCountry, set: (obj, value) => { obj.FromCountry = value; } } }, _FromCountry_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _FromState_decorators, { kind: "field", name: "FromState", static: false, private: false, access: { has: obj => "FromState" in obj, get: obj => obj.FromState, set: (obj, value) => { obj.FromState = value; } } }, _FromState_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _FromZip_decorators, { kind: "field", name: "FromZip", static: false, private: false, access: { has: obj => "FromZip" in obj, get: obj => obj.FromZip, set: (obj, value) => { obj.FromZip = value; } } }, _FromZip_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _To_decorators, { kind: "field", name: "To", static: false, private: false, access: { has: obj => "To" in obj, get: obj => obj.To, set: (obj, value) => { obj.To = value; } } }, _To_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _ToCity_decorators, { kind: "field", name: "ToCity", static: false, private: false, access: { has: obj => "ToCity" in obj, get: obj => obj.ToCity, set: (obj, value) => { obj.ToCity = value; } } }, _ToCity_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _ToCountry_decorators, { kind: "field", name: "ToCountry", static: false, private: false, access: { has: obj => "ToCountry" in obj, get: obj => obj.ToCountry, set: (obj, value) => { obj.ToCountry = value; } } }, _ToCountry_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _ToState_decorators, { kind: "field", name: "ToState", static: false, private: false, access: { has: obj => "ToState" in obj, get: obj => obj.ToState, set: (obj, value) => { obj.ToState = value; } } }, _ToState_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _ToZip_decorators, { kind: "field", name: "ToZip", static: false, private: false, access: { has: obj => "ToZip" in obj, get: obj => obj.ToZip, set: (obj, value) => { obj.ToZip = value; } } }, _ToZip_initializers, _instanceExtraInitializers);
        __esDecorate(null, null, _CreatedAt_decorators, { kind: "field", name: "CreatedAt", static: false, private: false, access: { has: obj => "CreatedAt" in obj, get: obj => obj.CreatedAt, set: (obj, value) => { obj.CreatedAt = value; } } }, _CreatedAt_initializers, _instanceExtraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name }, null, _classExtraInitializers);
        CallLog = _classThis = _classDescriptor.value;
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return CallLog = _classThis;
})();
export const CallLogSchema = SchemaFactory.createForClass(CallLog);
